export default {
  SET_ARTICLES: 'SET_ALL_ARTICLES',
  ADD_ARTICLE: 'ADD_ARTICLE',
  LOGIN_USER: 'LOGIN_USER',
  SET_SINGLE: 'SET_SINGLE_ARTICLE',
  ADD_COMMENT: 'ADD-ARTICLE-COMMENT',
  SET_COMMENTS: 'SET_ARTICLE_COMMENTS',
};
